from types import TracebackType

class PostgresContainer:
    def __init__(self, image: str) -> None: ...
    def __enter__(self) -> PostgresContainer: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def get_connection_url(self) -> str: ...
