# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from generated.warehouse_api_client.models.package_dimensions import PackageDimensions
from pydantic import BaseModel, Field


class PackageDetails(BaseModel):
    weightKg: float = Field(...)
    dimensions: PackageDimensions = Field(...)
