# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from pydantic import BaseModel, Field


class PackageDimensions(BaseModel):
    lengthCm: int = Field(...)
    widthCm: int = Field(...)
    heightCm: int = Field(...)
