# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from pydantic import BaseModel, Field


class ShelfItemOutput(BaseModel):
    itemId: str = Field(...)
    name: str = Field(...)
