# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from generated.http.models.media_attachment import MediaAttachment
from generated.http.models.postal_address import PostalAddress
from pydantic import BaseModel, Field


class ContentOutput(BaseModel):
    contentId: str = Field(...)
    title: str = Field(...)
    authorAddress: PostalAddress = Field(...)
    attachment: MediaAttachment = Field(...)
