# Generated by smithplates HTTP codegen for unknown.
# Service: example#WidgetApi
# Do not edit manually.
from fastapi import Request
from fastapi.responses import JSONResponse

from .api_exceptions import NotImplementedApiError


async def fallback_api_exception_handler(_request: Request, exc: Exception) -> JSONResponse:
    if isinstance(exc, NotImplementedApiError):
        return JSONResponse(status_code=501, content={"message": str(exc)})
    return JSONResponse(status_code=500, content={"message": str(exc)})
