# Generated by smithplates HTTP codegen for unknown.
# Service: example#WidgetApi
# Do not edit manually.
from fastapi import FastAPI
from generated.widget_api.apis.v1_widgets_api import router as v1_widgets_router


def create_app() -> FastAPI:
    app = FastAPI(
        title="WidgetApi",
        version="1",
    )
    app.include_router(v1_widgets_router)
    return app
