# Generated by smithplates HTTP codegen for unknown.
# Service: example#WidgetApi
# Do not edit manually.
from dataclasses import dataclass

from generated.widget_api.apis.v1_widgets_api_base import V1WidgetsApiServiceProtocol


@dataclass(frozen=True)
class ApiServices:
    v1_widgets_api: V1WidgetsApiServiceProtocol


def get_api_services() -> ApiServices:
    raise NotImplementedError("Wire ApiServices in application bootstrap")
