# Generated by smithplates HTTP codegen for unknown.
# Service: example#WidgetApi
# Do not edit manually.
OPERATION_HTTP_BINDINGS: dict[str, dict[str, object]] = {
    "GetWidget": {
        "success_status": 200,
        "method": "GET",
        "uri": "/v1/widgets/{id}",
    },
    "ListWidgets": {
        "success_status": 200,
        "method": "GET",
        "uri": "/v1/widgets",
    },
}
