from types import TracebackType

class PostgresContainer:
    username: str
    password: str
    dbname: str
    def __init__(self, image: str) -> None: ...
    def __enter__(self) -> PostgresContainer: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def get_connection_url(self) -> str: ...
    def get_container_host_ip(self) -> str: ...
    def get_exposed_port(self, port: int) -> str: ...
