# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from generated.content_api.models.media_attachment import MediaAttachment
from generated.content_api.models.postal_address import PostalAddress
from pydantic import BaseModel, Field


class CreateContentInput(BaseModel):
    title: str = Field(...)
    authorAddress: PostalAddress = Field(...)
    attachment: MediaAttachment = Field(...)
