# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from datetime import datetime
from typing import TypedDict

from generated.content_api.models.image_asset import ImageAsset


class MediaAttachmentCaption(TypedDict):
    caption: str


class MediaAttachmentImage(TypedDict):
    image: ImageAsset


class MediaAttachmentArchivedAt(TypedDict):
    archivedAt: datetime


MediaAttachment = MediaAttachmentCaption | MediaAttachmentImage | MediaAttachmentArchivedAt
