# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

import httpx
from generated.warehouse_api_client.client_response import parse_client_response
from generated.warehouse_api_client.models.item_details import ItemDetails
from generated.warehouse_api_client.models.shelf_item_output import ShelfItemOutput
from generated.warehouse_api_client.models.shelf_sku_output import ShelfSkuOutput
from generated.warehouse_api_client.operation_bindings import OPERATION_HTTP_BINDINGS
from pydantic import Field  # noqa: F401


class WarehouseApiClient:
    def __init__(self, client: httpx.AsyncClient, base_url: str) -> None:
        self._client = client
        self._base_url = base_url.rstrip("/")

    async def assign_shelf_sku(
        self,
        request_id: str | None,
        shelf_id: str,
        sku: str,
    ) -> ShelfSkuOutput:
        """POST with @httpHeader, one @httpLabel, and a primitive payload body member."""
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = str(request_id)
        response = await self._client.request(
            "POST",
            f"{self._base_url}/shelves/{shelf_id}/skus",
            headers=headers,
            json=sku,
        )
        return parse_client_response(
            response,
            OPERATION_HTTP_BINDINGS["assign_shelf_sku"],
        )

    async def create_shelf_item(
        self,
        idempotency_key: str | None,
        warehouse_id: str,
        shelf_id: str,
        details: ItemDetails,
    ) -> ShelfItemOutput:
        """POST with @httpHeader, @httpLabel path labels, and a nested structure @httpPayload body."""
        headers: dict[str, str] = {}
        if idempotency_key is not None:
            headers["X-Idempotency-Key"] = str(idempotency_key)
        response = await self._client.request(
            "POST",
            f"{self._base_url}/warehouses/{warehouse_id}/shelves/{shelf_id}/items",
            headers=headers,
            json=details.model_dump(mode="json", exclude_none=True),
        )
        return parse_client_response(
            response,
            OPERATION_HTTP_BINDINGS["create_shelf_item"],
        )
