# Generated by smithplates HTTP codegen. Do not edit.
from typing import Annotated, Protocol  # noqa: F401

from generated.http.models.asset_output import AssetOutput
from generated.http.models.asset_state_patch import AssetStatePatch
from generated.http.models.get_asset_content404 import GetAssetContent404
from generated.http.models.problem import Problem
from generated.http.models.redirect import Redirect
from pydantic import Field  # noqa: F401


class AssetsApiServiceProtocol(Protocol):
    async def get_asset(
        self,
        id: str,
    ) -> AssetOutput: ...
    async def get_asset_content(
        self,
        id: str,
    ) -> Redirect | GetAssetContent404: ...
    async def update_asset_state(
        self,
        id: str,
        body: AssetStatePatch,
    ) -> AssetOutput | Problem: ...
