flowchart TD
    SM["Smithy model"]
    SSP["smithplates-plugin"]

    SM --> SSP

    SSP --> SQLIR["SQL IR"]


    subgraph schema["Schema and migrations"]
        SQLIR --> DDL["Dialect-specific DDL"]
        SQLIR --> SchemaIT["Target language database schema integration tests"]
        
        Migration["Target language database migration engine<br/>(TODO: [#2](https://github.com/Jacoby6000/Smithplates/issues/2))"]
        DDL   -.-> Migration
        SQLIR -.-> Migration
    end

    subgraph services["SQL Database Service codegen"]
        SSP   --> SVCIR["Database services and operations IR"]
        SQLIR --> SVCIR
        
        MT["Scalate SSP templates"]
        SVCIR --> TLQM["Target Language Query Models"]
        MT    --> TLQM

        SVCIR --> Interfaces["Target language interfaces"]
        MT    --> Interfaces   
        TLQM  --> Interfaces

        SVCIR --> AbstractTests["Target language abstract test suites"]
        MT    --> AbstractTests
        TLQM  --> AbstractTests

        SVCIR --> DerivedQueries["Derived dialect-specific queries"]
        SQLIR --> DerivedQueries

        Interfaces     --> Impl["Dialect Specific Implementation"]
        MT             --> Impl        
        DerivedQueries --> Impl

        Migration      --> TestImpl["Target language test suite implementations"]
        MT             --> TestImpl
        DerivedQueries --> TestImpl
        AbstractTests  --> TestImpl

    end