# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

import httpx
from generated.warehouse_api_client.models.shelf_item_output import ShelfItemOutput
from generated.warehouse_api_client.models.shelf_sku_output import ShelfSkuOutput
from generated.warehouse_api_client.operation_bindings import ClientOperationHttpBinding
from pydantic import BaseModel


class ClientResponseError(Exception):
    """Raised when an HTTP response cannot be mapped to a generated API model."""


_MODEL_TYPES: dict[str, type[BaseModel]] = {
    "ShelfItemOutput": ShelfItemOutput,
    "ShelfSkuOutput": ShelfSkuOutput,
}


def parse_client_response(
    response: httpx.Response,
    binding: ClientOperationHttpBinding,
) -> BaseModel | None:
    """Map an HTTP response to a generated API model using Smithy-derived bindings."""
    if response.status_code == 204 or binding.variants_by_status.get(response.status_code) == "__empty__":
        response.raise_for_status()
        return None

    variant = binding.variant_for_status(response.status_code)
    type_name = binding.type_name_for_status(response.status_code)
    model_type = _resolve_model_type(type_name)

    if variant.media_type is None:
        if variant.header_bindings:
            payload = {
                member_name: response.headers.get(header_name) for member_name, header_name in variant.header_bindings
            }
            return model_type.model_validate(payload)
        response.raise_for_status()
        return None

    response.raise_for_status()
    body = response.json()
    return model_type.model_validate(body)


def _resolve_model_type(type_name: str) -> type[BaseModel]:
    model_type = _MODEL_TYPES.get(type_name)
    if model_type is None:
        msg = f"Unknown generated API model type {type_name!r}"
        raise ClientResponseError(msg)
    return model_type
