# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from pydantic import BaseModel, Field


class ProjectOutput(BaseModel):
    projectId: str = Field(...)
    name: str = Field(...)
