# Generated by smithplates HTTP codegen. Do not edit.
from typing import Annotated, Protocol  # noqa: F401

from generated.project_api.models.task_list_output import TaskListOutput
from generated.project_api.models.task_output import TaskOutput
from pydantic import Field  # noqa: F401


class ProjectTasksApiServiceProtocol(Protocol):
    async def create_project_task(
        self,
        project_id: str,
        title: str,
    ) -> TaskOutput: ...
    async def get_project_task(
        self,
        project_id: str,
        task_id: str,
    ) -> TaskOutput: ...
    async def list_project_tasks(
        self,
        project_id: str,
        page: str | None,
    ) -> TaskListOutput: ...
