# Generated by smithplates HTTP codegen. Do not edit.
from typing import Annotated, Protocol  # noqa: F401

from generated.project_api.models.create_project_input import CreateProjectInput
from generated.project_api.models.project_list_output import ProjectListOutput
from generated.project_api.models.project_output import ProjectOutput
from pydantic import Field  # noqa: F401


class ProjectsApiServiceProtocol(Protocol):
    async def create_project(
        self,
        create_project_input: CreateProjectInput,
    ) -> ProjectOutput: ...
    async def get_project(
        self,
        project_id: str,
    ) -> ProjectOutput: ...
    async def list_projects(
        self,
        limit: int | None,
    ) -> ProjectListOutput: ...
