# Generated by smithplates HTTP codegen for unknown.
# Service: example#WidgetApi
# Do not edit manually.
from typing import Annotated

from fastapi import APIRouter, Depends
from generated.widget_api.api_response import dispatch_api_response
from generated.widget_api.app_services import ApiServices, get_api_services
from generated.widget_api.operation_bindings import OPERATION_HTTP_BINDINGS

router = APIRouter()


@router.get(
    "/v1/widgets/{id}",
    responses={},
    response_model_by_alias=True,
)
async def get_widget(
    services: Annotated[ApiServices, Depends(get_api_services)],
) -> object:
    return dispatch_api_response(
        await services.v1_widgets_api.get_widget(),
        OPERATION_HTTP_BINDINGS["GetWidget"],
    )


@router.get(
    "/v1/widgets",
    responses={},
    response_model_by_alias=True,
)
async def list_widgets(
    services: Annotated[ApiServices, Depends(get_api_services)],
) -> object:
    return dispatch_api_response(
        await services.v1_widgets_api.list_widgets(),
        OPERATION_HTTP_BINDINGS["ListWidgets"],
    )
