# Generated by smithplates HTTP codegen for unknown.
# Service: example#WidgetApi
# Do not edit manually.
from typing import Annotated, Protocol  # noqa: F401

from pydantic import Field  # noqa: F401


class V1WidgetsApiServiceProtocol(Protocol):
    async def get_widget(
        self,
    ) -> object: ...
    async def list_widgets(
        self,
    ) -> object: ...
