# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from typing import TypedDict


class Problem(TypedDict, total=False):
    """RFC 9457 problem details object (`application/problem+json`)."""

    type: str
    title: str
    status: int
    detail: str
    instance: str
