package com.jacoby6000.smithplates.http.service.renderer

import com.jacoby6000.smithplates.http.model.HttpRouteGroup
import com.jacoby6000.smithplates.http.model.HttpStructure
import com.jacoby6000.smithplates.scalate.precompiler.ConfiguredTemplateEngine
import com.jacoby6000.smithplates.scalate.precompiler.ScalateTemplatePrecompiler
import org.fusesource.scalate.Template
import org.fusesource.scalate.TemplateEngine

import java.util.concurrent.ConcurrentHashMap

object ScalateSspTemplateEngine {
  private val compiledTemplateCache                                          = new ConcurrentHashMap[String, Template]()
  private def contextBindingPreamble(normalizedTemplateRoot: String): String =
    readClasspathTemplate(PythonTemplateNamespaces.commonPreambleClasspath).getOrElse("") +
      readClasspathTemplate(PythonTemplateNamespaces.namingPreambleClasspath(normalizedTemplateRoot)).getOrElse("")

  private def readClasspathTemplate(resourcePath: String): Option[String] =
    readClasspathTemplateOptional(normalizeResourcePath(resourcePath))

  def renderClasspathTemplate(
      templateClasspath: String,
      view: HttpCodegenTemplateView,
      templateRoot: Option[String] = None
  ): String =
    renderClasspathTemplateAttributes(templateClasspath, Map("ctx" -> view), templateRoot)

  def renderClasspathTemplateAttributes(
      templateClasspath: String,
      attributes: Map[String, Any],
      templateRoot: Option[String]
  ): String = {
    val normalizedTemplatePath = normalizeClasspathUri(templateClasspath)
    val resolvedTemplateRoot   =
      templateRoot
        .map(normalizeTemplateRoot)
        .getOrElse(inferTemplateRoot(normalizedTemplatePath))
    val templateUri            = templateUriRelativeToRoot(normalizedTemplatePath, resolvedTemplateRoot)
    val engine                 = templateEngine(resolvedTemplateRoot)
    val template               = compiledTemplateCache.computeIfAbsent(
      s"$resolvedTemplateRoot:$templateUri",
      _ => engine.load(templateUri)
    )
    val renderedBody           =
      normalizeRenderedOutput(
        engine.layout(templateUri, template, toObjectMap(attributes))
      )
    prependGeneratedFileHeader(attributes, resolvedTemplateRoot, renderedBody)
  }

  def classpathResourceExists(resourcePath: String): Boolean = {
    val normalized = normalizeResourcePath(resourcePath)
    Option(getClass.getResource(normalized)).isDefined
  }

  private def prependGeneratedFileHeader(
      attributes: Map[String, Any],
      templateRoot: String,
      renderedBody: String
  ): String = {
    val trimmedBody = renderedBody.stripTrailing()
    if (trimmedBody.startsWith("# Generated by smithplates HTTP codegen")) {
      if (trimmedBody.isEmpty) {
        trimmedBody
      } else {
        s"$trimmedBody\n"
      }
    } else if (trimmedBody.isEmpty) {
      trimmedBody
    } else {
      val serviceShapeId =
        attributes.get("ctx").collect { case view: HttpCodegenTemplateView => view.service.shapeId }.getOrElse {
          software.amazon.smithy.model.shapes.ShapeId.from("smithy.api#Unit")
        }
      val header         =
        ScalateTemplateHelpers.generatedFileHeader(
          serviceShapeId,
          ScalateTemplateHelpers.languageFromTemplateRoot(templateRoot)
        )
      s"$header\n$trimmedBody\n"
    }
  }

  /** Builds a template engine configured exactly like the runtime engine for ahead-of-time precompilation. Reusing this
    * factory guarantees the precompiled class names (driven by `packagePrefix`, bindings and template URI) match what
    * the runtime [[org.fusesource.scalate.TemplateEngine]] resolves.
    */
  def precompilationEngine(templateRoot: String): TemplateEngine =
    templateEngine(normalizeTemplateRoot(templateRoot))

  private def templateEngine(normalizedTemplateRoot: String): TemplateEngine = {
    val created = new ConfiguredTemplateEngine
    created.allowCaching = true
    created.allowReload = false
    created.escapeMarkup = false
    created.packagePrefix = ScalateTemplatePrecompiler.packagePrefix(normalizedTemplateRoot)
    created.resourceLoader = new PreambleTemplateRootResourceLoader(
      getClass.getClassLoader,
      normalizedTemplateRoot,
      contextBindingPreamble(normalizedTemplateRoot)
    )
    created
  }

  private def readClasspathTemplateOptional(resourcePath: String): Option[String] =
    Option(getClass.getResourceAsStream(normalizeResourcePath(resourcePath))).map { stream =>
      try readStream(stream)
      finally stream.close()
    }

  private def readStream(stream: java.io.InputStream): String =
    scala.io.Source.fromInputStream(stream, "UTF-8").mkString

  private def normalizeClasspathUri(templateClasspath: String): String =
    templateClasspath.stripPrefix("classpath:")

  private def normalizeTemplateRoot(templateRoot: String): String =
    templateRoot.stripPrefix("classpath:").stripPrefix("/").stripSuffix("/")

  private def inferTemplateRoot(templateClasspath: String): String = {
    val normalized = normalizeTemplateRoot(templateClasspath)
    val segments   = normalized.split("/").toList
    segments match {
      case "python" :: "src" :: feature :: _               =>
        s"python/src/$feature"
      case "templates" :: language :: "src" :: "http" :: _ =>
        s"templates/$language/src/http"
      case _ if segments.length >= 2                       =>
        segments.take(2).mkString("/")
      case _                                               =>
        normalized
    }
  }

  private def templateUriRelativeToRoot(templateClasspath: String, templateRoot: String): String = {
    val normalizedTemplate = normalizeTemplateRoot(templateClasspath)
    val root               = normalizeTemplateRoot(templateRoot)
    if (normalizedTemplate.startsWith(s"$root/")) {
      normalizedTemplate.stripPrefix(s"$root/")
    } else {
      normalizedTemplate
    }
  }

  private def normalizeResourcePath(resourcePath: String): String =
    if (resourcePath.startsWith("/")) {
      resourcePath
    } else {
      s"/$resourcePath"
    }

  private def normalizeRenderedOutput(output: String): String = {
    val trimmed = output.stripTrailing()
    if (trimmed.isEmpty) {
      trimmed
    } else {
      s"$trimmed\n"
    }
  }

  private def toObjectMap(attributes: Map[String, Any]): Map[String, Object] =
    attributes.map { case (key, value) =>
      key -> (value match {
        case view: HttpCodegenTemplateView                                  => view.asInstanceOf[Object]
        case routeGroup: HttpRouteGroup                                     => routeGroup.asInstanceOf[Object]
        case operation: com.jacoby6000.smithplates.http.model.HttpOperation =>
          operation.asInstanceOf[Object]
        case structure: HttpStructure                                       => structure.asInstanceOf[Object]
        case other                                                          => other.asInstanceOf[Object]
      })
    }
}
