package com.jacoby6000.smithplates.http.service.renderer

import software.amazon.smithy.model.shapes.ShapeId

object ScalateTemplateHelpers {
  def generatedFileHeader(serviceShapeId: ShapeId, language: String): String = {
    val _ = (serviceShapeId, language)
    "# Generated by smithplates HTTP codegen. Do not edit."
  }

  def languageFromTemplateRoot(templateRoot: String): String =
    templateRoot.split("/").lift(1).getOrElse("unknown")
}
