package com.jacoby6000.smithplates.http.service.renderer

import software.amazon.smithy.model.shapes.ShapeId

object ScalateTemplateHelpers {
  def generatedFileHeader(serviceShapeId: ShapeId, language: String): String =
    s"""# Generated by smithplates HTTP codegen for $language.
# Service: ${serviceShapeId.toString}
# Do not edit manually."""

  def languageFromTemplateRoot(templateRoot: String): String =
    templateRoot.split("/").lift(1).getOrElse("unknown")
}
