package com.jacoby6000.smithplates.http.service.renderer

import software.amazon.smithy.model.shapes.ShapeId

object ScalateTemplateHelpers {
  def generatedFileHeader(serviceShapeId: ShapeId, language: String): String = {
    val _ = (serviceShapeId, language)
    "# Generated by smithplates HTTP codegen. Do not edit."
  }

  def languageFromTemplateRoot(templateRoot: String): String = {
    val normalized =
      templateRoot.stripPrefix("classpath:").stripPrefix("/").stripSuffix("/")
    normalized.split("/").toList match {
      case "python" :: "src" :: _ => "python"
      case _ :: language :: _     => language
      case language :: _          => language
      case _                      => "unknown"
    }
  }
}
