# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass

from pydantic import BaseModel


@dataclass(frozen=True)
class ResponseVariantBinding:
    status_code: int
    media_type: str | None
    header_bindings: tuple[tuple[str, str], ...]
    static_headers: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class OperationHttpBinding:
    variants_by_type_name: dict[str, ResponseVariantBinding]

    def variant_for(self, response: BaseModel | None) -> ResponseVariantBinding:
        if response is None:
            binding = self.variants_by_type_name.get(
                "__empty__",
            )
            if binding is None:
                msg = "Service returned None but operation has no empty-response binding"
                raise TypeError(msg)
            return binding
        type_name = type(response).__name__
        binding = self.variants_by_type_name.get(type_name)
        if binding is None:
            msg = f"No HTTP binding registered for response type {type_name!r}"
            raise KeyError(msg)
        return binding


OPERATION_HTTP_BINDINGS: dict[str, OperationHttpBinding] = {
    "create_project_task": OperationHttpBinding(
        variants_by_type_name={
            "TaskOutput": ResponseVariantBinding(
                status_code=201,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "CreateProjectTask": OperationHttpBinding(
        variants_by_type_name={
            "TaskOutput": ResponseVariantBinding(
                status_code=201,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "get_project_task": OperationHttpBinding(
        variants_by_type_name={
            "TaskOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "GetProjectTask": OperationHttpBinding(
        variants_by_type_name={
            "TaskOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "list_project_tasks": OperationHttpBinding(
        variants_by_type_name={
            "TaskListOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "ListProjectTasks": OperationHttpBinding(
        variants_by_type_name={
            "TaskListOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "create_project": OperationHttpBinding(
        variants_by_type_name={
            "ProjectOutput": ResponseVariantBinding(
                status_code=201,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "CreateProject": OperationHttpBinding(
        variants_by_type_name={
            "ProjectOutput": ResponseVariantBinding(
                status_code=201,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "get_project": OperationHttpBinding(
        variants_by_type_name={
            "ProjectOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "GetProject": OperationHttpBinding(
        variants_by_type_name={
            "ProjectOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "list_projects": OperationHttpBinding(
        variants_by_type_name={
            "ProjectListOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "ListProjects": OperationHttpBinding(
        variants_by_type_name={
            "ProjectListOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
}
