# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations


class NotImplementedApiError(Exception):
    """Raised by stub service code; converted to 501 by fallback API exception handlers."""
