# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass

from pydantic import BaseModel


@dataclass(frozen=True)
class ResponseVariantBinding:
    status_code: int
    media_type: str | None
    header_bindings: tuple[tuple[str, str], ...]
    static_headers: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class OperationHttpBinding:
    variants_by_type_name: dict[str, ResponseVariantBinding]

    def variant_for(self, response: BaseModel | None) -> ResponseVariantBinding:
        if response is None:
            binding = self.variants_by_type_name.get(
                "__empty__",
            )
            if binding is None:
                msg = "Service returned None but operation has no empty-response binding"
                raise TypeError(msg)
            return binding
        type_name = type(response).__name__
        binding = self.variants_by_type_name.get(type_name)
        if binding is None:
            msg = f"No HTTP binding registered for response type {type_name!r}"
            raise KeyError(msg)
        return binding


OPERATION_HTTP_BINDINGS: dict[str, OperationHttpBinding] = {
    "get_project_asset": OperationHttpBinding(
        variants_by_type_name={
            "AssetOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "GetProjectAsset": OperationHttpBinding(
        variants_by_type_name={
            "AssetOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "get_project_asset_content": OperationHttpBinding(
        variants_by_type_name={
            "Redirect": ResponseVariantBinding(
                status_code=302,
                media_type=None,
                header_bindings=(("url", "Location"),),
                static_headers=(),
            ),
        },
    ),
    "GetProjectAssetContent": OperationHttpBinding(
        variants_by_type_name={
            "Redirect": ResponseVariantBinding(
                status_code=302,
                media_type=None,
                header_bindings=(("url", "Location"),),
                static_headers=(),
            ),
        },
    ),
    "list_asset_events": OperationHttpBinding(
        variants_by_type_name={
            "AssetEventListOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
    "ListAssetEvents": OperationHttpBinding(
        variants_by_type_name={
            "AssetEventListOutput": ResponseVariantBinding(
                status_code=200,
                media_type="application/json",
                header_bindings=(),
                static_headers=(),
            ),
        },
    ),
}
