# Generated by smithplates HTTP codegen. Do not edit.
from typing import Annotated, Protocol  # noqa: F401

from generated.example.content_output import ContentOutput
from generated.example.create_content_input import CreateContentInput
from pydantic import Field  # noqa: F401


class ContentApiServiceProtocol(Protocol):
    async def create_content(
        self,
        create_content_input: CreateContentInput,
    ) -> ContentOutput: ...
    async def get_content(
        self,
        content_id: str,
    ) -> ContentOutput: ...
