# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from generated.warehouse_api.models.package_details import PackageDetails
from pydantic import BaseModel, Field


class ItemDetails(BaseModel):
    name: str = Field(...)
    package: PackageDetails = Field(...)
