# Generated by smithplates HTTP codegen. Do not edit.

from __future__ import annotations

from pydantic import BaseModel, Field


class Problem(BaseModel):
    """RFC 7807 problem details used by fallback API exception handlers."""

    type: str | None = Field(default=None)
    title: str | None = Field(default=None)
    status: int | None = Field(default=None)
    detail: str | None = Field(default=None)
    instance: str | None = Field(default=None)
